# Brightness Schedule Configuration
# Format: 
#   time: "HH:MM" (24-hour format)
#   brightness: 0-100 (percentage)
# 
# Schedule for HP M24f FHD monitor connected to MacBook M1

schedule:
  - time: "09:00"  # Morning
    brightness: 100
    
  - time: "18:00"  # Early evening
    brightness: 75
    
  - time: "20:00"  # Evening
    brightness: 50
    
  - time: "22:00"  # Night
    brightness: 30 